### ISSUE TITLE
Different result of Calling DiffusionMap

### ISSUE THREAD

**Issue by RuixiangLiu01** [theislab/destiny#33]
Hello developer,I found that every time when I calling DiffusionMap function, I get the different result about eigenvector.But as I know, these vector was computed from eigen decomposition from a Matrix. So, could someone explain why this would happen?How can I do to solve this problem.I installed destiny with `devtools::install_github('theislab/destiny')`.Thanks!
![image](https://user-images.githubusercontent.com/37862626/87895868-2a6f1d00-ca79-11ea-8da4-da0aba14dc27.png)
![image](https://user-images.githubusercontent.com/37862626/87895871-31962b00-ca79-11ea-9c78-f9e454facb8c.png)

**Comment by flying-sheep** [comment]
The implementation of Eigen decomposition I use is approximate and nondeterministic (everything else would be unbearably slow). The newest destiny versions should make sure that `set.seed(...)` works as expected and results in the same decomposition being found, see #5 and yixuan/RSpectra#14

I can’t completely guarantee it though, since 3rd party libraries sometimes don’t respect it.

**Comment by RuixiangLiu01** [comment]
> The implementation of Eigen decomposition I use is approximate and nondeterministic (everything else would be unbearably slow). The newest destiny versions should make sure that `set.seed(...)` works as expected and results in the same decomposition being found, see #5 and [yixuan/RSpectra#14](https://github.com/yixuan/RSpectra/issues/14)
> 
> I can’t completely guarantee it though, since 3rd party libraries sometimes don’t respect it.

sorry for update late,  I remove destiny and reinstall with `devtools::install_github('theislab/destiny')`， the problem was solved.Thank u so much!

**Comment by flying-sheep** [comment]
No problem, great that it works for you!
